services:
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${BACKEND_DB_USERNAME}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
      - POSTGRES_DB=${BACKEND_DB_NAME}
    ports: ["${BACKEND_DB_PORT}:${BACKEND_DB_PORT}"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
  backend:
    build: ./backend
    ports: ["${BACKEND_PORT}:${BACKEND_PORT}"]
    depends_on:
      - database
    environment:
      - PORT=${BACKEND_PORT}
      - DB_URL=jdbc:postgresql://database:${BACKEND_DB_PORT}/${BACKEND_DB_NAME}
      - DB_USERNAME=${BACKEND_DB_USERNAME}
      - DB_PASSWORD=${BACKEND_DB_PASSWORD}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_EXPIRATION_MS=${BACKEND_JWT_EXPIRATION_MS}
      - FRONTEND_URL=http://frontend:${FRONTEND_PORT}
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT_TARGET}
  frontend:
    build:
      context: ./frontend
      target: ${ENVIRONMENT_TARGET}
    ports: ["${FRONTEND_PORT}:${FRONTEND_PORT}"]
    depends_on:
      - backend
    environment:
      - BACKEND_API_URL=http://backend:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
      - ALLOWED_HOSTNAMES=${ALLOWED_HOSTNAMES}
volumes:
  db_data:
